### ISSUE TITLE
Simplify register page

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#83]
@cncpl suggested we should simplify the register page according to the picture.

Important:

- Check which fields could be omitted

- Rearrange register page according to the picture

![loginseite](https://user-images.githubusercontent.com/17025347/46878337-4de84b00-ce43-11e8-88e0-d45ad65ecec2.png)

**Comment by ChristinaSi** [comment]
I assigned the issue to you, @dboehmer because you have to check the necessary fields first.

**Comment by dboehmer** [comment]
Currently the database design and the registration process actually needs all of these fields. I am not quite sure which one we could drop.

I've been thinking about the properties of a user for a long time because it seems to be hard for people to understand *username* and *display name*. I copied this concept from Twitter: People will need one's username to grant them permissions on their projects. That's why usernames need to be

* unique,
* unambigious and
* easy to type on any keyboard and
* should be static.

But human names aren't–so many platforms allow to set a display name that might
* change,
* include special characters or
* be non-unique.

Of course we need an e-mail address to provide simple account management like password reset or notifications.

Is it a good idea to require users to enter other users' e-mail address to identify them? They shouldn't need to know that, I think.

What else could be used to identify other users? At Facebook there's no such thing as a username (I believe) but Facebook knows your known contacts AKA "friends". I think Coocook won't benefit from connecting users as "friends" in order to give them permissions.

So currently the database requires that all of username, display name and e-mail address. Because I have no idea how to save a property, I return this issue.

**Comment by ChristinaSi** [comment]
@dboehmer  Is there still something to do here? I moved the labels to the left today.

**Comment by dboehmer** [comment]
I didn't close the issue earlier in case you had any concerns:-)
