### ISSUE TITLE
Internal server error at import

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#99]
Today I tried to import all items of the project "Sola 2019 Woche 1 - Teens" into my new private project ("Mittagessen Gemeinde_082019"). It showed an internal server error. After just selecting recipes for import (with all dependent items) it worked. (I excluded tags and shop sections).

**Comment by dboehmer** [comment]
Thank you for this report and sorry for the long wait.

We've had issues with this before. The cause is that in the source project a recipe was linked to tags that belong to other projects&mdash;this should never happen. During import the connection is being copied but the referenced tag does not exist in the target project either.

Now I think I did everything I can:
* removed the invalid tag connection in live database
* fixed the assignment of tags in 51e9d71ed5fe70a82c7593eb35aab0292b5c3870
* created a daily cronjob that runs `script/coocook_dbck.pl` which actually detects the invalid connections and notifies me
* created issue #101 to make sure I do not miss internal errors in the future
